services:
  - type: web
    runtime: static
    name: tablequest
    repo: https://github.com/Noob1Minecraft/tablequest
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: BASE_PATH
        value: /
      - key: SKIP_INSTALL_DEPS
        value: "true"
    headers:
      - path: /manifest.webmanifest
        name: Content-Type
        value: application/manifest+json
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate, no-transform
