import type { Locale } from "../types";
const en = {
  moment: "Restaurant Moment",
  demo: "Demo · Restaurant prototype",
  momentNote:
    "A little something from the restaurant could end your evening beautifully. This is a demonstration, not an available offer.",
  dessert: "Dessert surprise",
  coffee: "Coffee pairing",
  mocktail: "Mocktail upgrade",
  request: "Try a bonus request",
  pending: "One moment…",
  receipt: "Demo request created",
  notSent:
    "Nothing was sent to restaurant staff. No order or payment was made.",
  failed: "Could not save this demo. Please try again.",
  improve: "Help improve TableQuest",
  optional: "Optional · a little more detail",
  stars: "Your rating · 1–5",
  category: "What is your feedback about?",
  none: "Choose a category",
  content: "Content",
  atmosphere: "Atmosphere",
  usability: "Usability",
  restaurant: "Restaurant experience",
  comment: "What got in the way? (optional)",
  sending: "Saving…",
  local: "Your answer stays on this device.",
  external:
    "Your answer is saved here and sent to the configured feedback service, including table, venue, language and game mode. Please leave out personal details.",
  sent: "Feedback sent. A copy is saved on this device.",
  fallback:
    "Saved on this device. Delivery failed; it will not be resent automatically.",
  admin: "Feedback · Local prototype",
  adminNote:
    "Only feedback stored in this browser on this domain. No shared restaurant analytics, account or access protection.",
  total: "Responses",
  average: "Average explicit rating",
  rated: "Rated responses",
  export: "Export CSV",
  empty: "No feedback saved here yet.",
  back: "Back to guests",
  normal: "Guest feedback",
  demoData: "Demo feedback",
  unknown: "Not specified",
  table: "Table",
  venue: "Venue",
  timestamp: "Time",
  language: "Language",
  mode: "Mode",
  satisfaction: "Did it make the evening better?",
  good: "Yes",
  okay: "A little",
  bad: "No",
};
type Copy = { [K in keyof typeof en]: string };
const ru: Copy = {
  moment: "Момент от ресторана",
  demo: "Демо · Прототип для ресторана",
  momentNote:
    "Небольшой комплимент заведения мог бы завершить ваш вечер. Это демонстрация, а не действующее предложение.",
  dessert: "Десерт-сюрприз",
  coffee: "Кофейная пара",
  mocktail: "Особый безалкогольный коктейль",
  request: "Попробовать запрос бонуса",
  pending: "Один момент…",
  receipt: "Демо-запрос создан",
  notSent: "Персоналу ничего не отправлено. Заказ и оплата не оформлены.",
  failed: "Не удалось сохранить демо. Попробуйте ещё раз.",
  improve: "Помогите улучшить TableQuest",
  optional: "Необязательно · чуть подробнее",
  stars: "Ваша оценка · 1–5",
  category: "О чём ваш отзыв?",
  none: "Выберите категорию",
  content: "Задания",
  atmosphere: "Атмосфера",
  usability: "Удобство",
  restaurant: "Впечатление от ресторана",
  comment: "Что помешало? (необязательно)",
  sending: "Сохраняем…",
  local: "Ваш ответ останется на этом устройстве.",
  external:
    "Ответ сохранится здесь и будет отправлен в подключённый сервис отзывов вместе со столом, заведением, языком и режимом игры. Не указывайте личные данные.",
  sent: "Отзыв отправлен. Копия сохранена на устройстве.",
  fallback:
    "Сохранено на устройстве. Отправка не удалась; автоматической повторной отправки не будет.",
  admin: "Отзывы · Локальный прототип",
  adminNote:
    "Только отзывы этого браузера на этом домене. Без общей аналитики ресторана, аккаунтов и защиты доступа.",
  total: "Ответов",
  average: "Средняя явная оценка",
  rated: "Ответов с оценкой",
  export: "Экспорт CSV",
  empty: "Здесь ещё нет сохранённых отзывов.",
  back: "К гостевому режиму",
  normal: "Отзывы гостей",
  demoData: "Демо-отзывы",
  unknown: "Не указано",
  table: "Стол",
  venue: "Заведение",
  timestamp: "Время",
  language: "Язык",
  mode: "Режим",
  satisfaction: "Встреча стала интереснее?",
  good: "Да",
  okay: "Немного",
  bad: "Нет",
};
const kk: Copy = {
  moment: "Мейрамхана сәті",
  demo: "Демо · Мейрамхана прототипі",
  momentNote:
    "Мейрамхананың шағын сыйы кешті әдемі аяқтауы мүмкін. Бұл — таныстыру үлгісі, нақты ұсыныс емес.",
  dessert: "Тосын десерт",
  coffee: "Кофеге үйлесетін дәм",
  mocktail: "Ерекше алкогольсіз коктейль",
  request: "Бонус сұрауын байқап көру",
  pending: "Бір сәт…",
  receipt: "Демо-сұрау жасалды",
  notSent:
    "Қызметкерлерге ештеңе жіберілген жоқ. Тапсырыс пен төлем жасалмады.",
  failed: "Демоны сақтау мүмкін болмады. Қайта көріңіз.",
  improve: "TableQuest-ті жақсартуға көмектесіңіз",
  optional: "Міндетті емес · толығырақ",
  stars: "Бағаңыз · 1–5",
  category: "Пікіріңіз не туралы?",
  none: "Санатты таңдаңыз",
  content: "Тапсырмалар",
  atmosphere: "Атмосфера",
  usability: "Қолайлылық",
  restaurant: "Мейрамхана әсері",
  comment: "Не кедергі болды? (міндетті емес)",
  sending: "Сақталуда…",
  local: "Жауабыңыз осы құрылғыда қалады.",
  external:
    "Жауап осында сақталып, үстел, орын, тіл және ойын режимімен бірге қосылған пікір сервисіне жіберіледі. Жеке деректерді жазбаңыз.",
  sent: "Пікір жіберілді. Көшірмесі құрылғыда сақталды.",
  fallback:
    "Құрылғыда сақталды. Жіберілмеді; автоматты түрде қайта жіберілмейді.",
  admin: "Пікірлер · Жергілікті прототип",
  adminNote:
    "Тек осы домендегі осы браузердің пікірлері. Ортақ мейрамхана аналитикасы, аккаунт және кіру қорғанысы жоқ.",
  total: "Жауаптар",
  average: "Қойылған бағалардың орташа мәні",
  rated: "Бағасы бар жауаптар",
  export: "CSV экспорттау",
  empty: "Әзірге сақталған пікір жоқ.",
  back: "Қонақ режиміне",
  normal: "Қонақ пікірлері",
  demoData: "Демо-пікірлер",
  unknown: "Көрсетілмеген",
  table: "Үстел",
  venue: "Орын",
  timestamp: "Уақыт",
  language: "Тіл",
  mode: "Режим",
  satisfaction: "Кездесу қызығырақ болды ма?",
  good: "Иә",
  okay: "Аздап",
  bad: "Жоқ",
};
export const hospitalityCopy: Record<Locale, Copy> = { ru, kk, en };
